version: "3.7"

services:
  app:
    build: .
    ports:
      - "8090:8090"
    networks:
      - my-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
      MYSQL_DB: demo
    ports:
      - "3305:3306"
    networks:
      - my-network
    volumes:
      - mysql-student-data:/var/lib/mysql/data

networks:
  my-network:
    driver: bridge

volumes:
  mysql-student-data: